version: 2
jobs:
  unit_tests:
    docker:
      - image: codebrew28/flask-example-scraper
    steps:
      - checkout
      - run:
        command: |
          cd microservices
          pytest
workflows:
  version: 2
  build_test:
    jobs:
      - unit_tests
