version: 2
jobs:
  microservice_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            pipenv install --skip-lock
            pipenv run pytest
  microservice_lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            pipenv install --skip-lock
            pipenv run black . --check
workflows:
  version: 2
  build_tool:
    jobs:
      - microservice_test
      - microservice_lint
