version: 2
jobs:
  unit_tests:
    docker:
      - image: codebrew28/flask-example-scraper
    steps:
      - checkout
      - run: python3 -m unittest discover -t . -p "*_test.py"
workflows:
  version: 2
  build_test:
    jobs:
      - unit_tests
