version: 2
jobs:
  microservice_unit_tests:
    docker:
      - image: codebrew28/flask-example-scraper
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            pytest
  microservice_lint:
    docker:
      - image: codebrew28/flask-example-scraper
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            black .
workflows:
  version: 2
  build_tool:
    jobs:
      - microservice_unit_tests
      - microservice_lint
