version: 2
jobs:
  unit_tests:
    docker:
      - image: codebrew28/flask-example-scraper
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            pytest
  lint:
    docker:
      - image: codebrew28/flask-example-scraper
    steps:
      - checkout
      - run:
          command: |
            black .
workflows:
  version: 2
  build_tool:
    jobs:
      - unit_tests
      - lint
