version: 2
jobs:
  unit_tests:
    steps:
      - checkout
      - run:
        command: |
          cd microservices
          pytest
  lint:
    steps:
      - checkout
      - run:
        command: |
          black .
workflows:
  version: 2
  build_tool:
    jobs:
      - unit_tests
      - lint
